### ISSUE TITLE
Dropdown CSS / HTML

### ISSUE THREAD

**Issue by meodai** [dfinity/internet-identity#1169]
In the pull request https://github.com/dfinity/internet-identity/pull/1166 I had made a dropdown list that we will not merge for now, since it would make the PR too big.

I leave this here mainly for myself (or whoever needs it first)

```css
.c-dropdown {
  position: relative;
}

.c-dropdown__trigger {
  z-index: calc(var(--vz-tooltip) + 2);
  transition: 100ms color linear;
}

.c-dropdown:hover .c-dropdown__trigger,
.c-dropdown:focus-within .c-dropdown__trigger {
  color: var(--rc-interaction);
}

.c-dropdown::after {
  opacity: 0;
  content: "";
  position: absolute;
  top: calc(var(--vs-bezel) * -1);
  bottom: 0;
  height: calc(100% - var(--vs-bezel));
  width: 100%;
  padding: var(--vs-bezel);
  right: calc(var(--vs-bezel) * -1);
  background: var(--rc-background);
  /*border: var(--vs-line) solid rgba(0, 0, 0, 0.1);*/
  border-bottom-color: var(--rc-background);
  z-index: calc(var(--vz-tooltip) + 1);
  box-sizing: content-box;
  pointer-events: none;
}

.c-dropdown__menu {
  opacity: 0;
  position: absolute;
  top: 100%;
  right: calc(var(--vs-bezel) * -1);
  z-index: var(--vz-tooltip);
  min-width: 100%;
  width: max-content;
  background-color: var(--rc-background);
  border-radius: var(--border-radius);
  padding: 0 var(--vs-bezel);
  margin-top: calc(-1 * var(--vs-line));
  text-align: right;
  pointer-events: none;
}

.c-dropdown:hover .c-dropdown__menu,
.c-dropdown:focus-within .c-dropdown__menu,
.c-dropdown:hover::after,
.c-dropdown:focus-within::after {
  opacity: 1;
  visibility: visible;
  pointer-events: auto;
}

.c-dropdown__menu::before {
  z-index: -1;
  content: "";
  position: absolute;
  inset: 0;
  box-shadow: 0 1rem 3rem rgba(0, 0, 0, 0.3);
}

.c-dropdown__item {
  display: block;
  padding: calc(var(--vs-bezel) * 0.75) 0;
  color: var(--rc-text);
  text-decoration: none;
}

.c-dropdown__item + .c-dropdown__item {
  border-top: var(--vs-line) solid var(--rc-line);
}

.c-dropdown__button {
  display: block;
  color: var(--rc-text);
  padding: 0.1em calc(var(--vs-bezel) * 0.5) 0;
  text-align: left;
  width: 100%;
  font-size: 0.75em;
  transition: color 100ms linear;
}

.c-dropdown__button:hover {
  color: var(--rc-interaction);
}
```

```html
<li class="c-action-list__item">
    <span class="c-action-list__label">Actionable List Item</span>
    <span class="c-action-list__action c-dropdown">
      <button
        class="c-dropdown__trigger"
        aria-expanded="false"
        aria-controls="dropdown-i"
      >
        ${settingsIcon}
      </button>
      <ul class="c-dropdown__menu" id="dropdown-i">
        <li class="c-dropdown__item">
          <button class="c-dropdown__button">Delete Anchor</button>
        </li>
        <li class="c-dropdown__item">
          <button class="c-dropdown__button">Lock Anchor</button>
        </li>
      </ul>
    </span>
  </li>
```
