### ISSUE TITLE
Add nicer style to "main card"

### ISSUE THREAD

**Issue by meodai** [dfinity/internet-identity#841]
Since we will not ship this, but I have already prepared it to test it. I am leaving this here, along with a screenshot for future reference.

```css
.c-card--highlight {
  background-color: var(--rc-background-transparent);
  border: var(--vs-line) solid var(--rc-line);
}

.c-card--highlight::before {
  content: " ";
  position: absolute;
  z-index: var(--vz-backdrop);
  top: 50%;
  left: 50%;
  width: 120%;
  aspect-ratio: 1;
  transform: translate(-50%, -50%);
  border-radius: 50%;
  background: linear-gradient(145deg, var(--rg-brand));
  filter: blur(8rem);
}
```

<img width="886" alt="Screenshot" src="https://user-images.githubusercontent.com/608386/187003869-ba6f8c35-65c8-4a35-95e5-cd7dbe9d7ad9.png">

vs. the current "redesigned" state:
<img width="886" alt="Screenshot2" src="https://user-images.githubusercontent.com/608386/187004259-f1248b0e-a012-48bc-8b9e-86018f7512c2.png">

**Comment by meodai** [comment]
along with a super simple dark mode:
```css
@media (prefers-color-scheme: dark) {
  :root {
    --rc-text: var(--rc-light);

    --rc-background: var(--rc-dark);
    --rc-background-transparent: var(--rc-dark-transparent);

    --rc-line: var(--rc-dark);
    --rc-line-inverted: var(--c-light);

    --rc-button: var(--rc-light);
    --rc-onButton: var(--rc-dark);
  }
}
```
<img width="885" alt="Screenshot3" src="https://user-images.githubusercontent.com/608386/187004788-56c862c7-7b59-4a8f-b423-c4719c71eaa0.png">
